source "${LOAD_CONF_PATH}"

"${BASH_SAY_HELLO_PATH}" "${NAME_1}"
"${BASH_SAY_HELLO_PATH}" "${NAME_2}"
"${BASH_SAY_HELLO_PATH}" "${NAME_3}"
"${BASH_SAY_HELLO_PATH}" "${NAME_4}"
"${BASH_SAY_HELLO_PATH}" "${NAME_5}"

"${NODE_SAY_HELLO_PATH}" "${NAME_1}"
