# This file has been generated by node2nix 1.11.1. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "chalk-5.2.0" = {
      name = "chalk";
      packageName = "chalk";
      version = "5.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/chalk/-/chalk-5.2.0.tgz";
        sha512 = "ree3Gqw/nazQAPuJJEy+avdl7QfZMcUvmHIKgEZkGL+xOBzRvup5Hxo6LHuMceSxOabuJLJm5Yp/92R9eMmMvA==";
      };
    };
  };
  args = {
    name = "node-lib";
    packageName = "node-lib";
    version = "1.0.0";
    src = ./.;
    dependencies = [
      sources."chalk-5.2.0"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Prints a greeting.";
      license = "ISC";
    };
    production = true;
    bypassCache = true;
    reconstructLock = false;
  };
in
{
  args = args;
  sources = sources;
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
  nodeDependencies = nodeEnv.buildNodeDependencies (lib.overrideExisting args {
    src = stdenv.mkDerivation {
      name = args.name + "-package-json";
      src = nix-gitignore.gitignoreSourcePure [
        "*"
        "!package.json"
        "!package-lock.json"
      ] args.src;
      dontBuild = true;
      installPhase = "mkdir -p $out; cp -r ./* $out;";
    };
  });
}
