name: Quality Checks

on:
  pull_request:
    branches:
      - master

jobs:
  linting:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Nix
        uses: cachix/install-nix-action@v18
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
            substituters = https://cache.nixos.org/
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Check if nixifying and formatting effects have been committed
        run: |
          ./nixify.sh 
          ./format.sh
          ./is-working-tree-clean.sh
      - name: Run linters
        run: |
          ./lint.sh
